jobs: 20
cluster:
    sbatch
        --parsable # output only job id number and cluster name 
        --partition {resources.partition}
        --time {resources.time_min}
        --mem {resources.mem_mb}
        --cpus-per-task {resources.cpus}
        --output logs/slurm/slurm-%j-{rule}.out
        --account kima
default-resources: 
    - cpus=2
    - mem_mb=512
    - partition=inv-iranui-fast,inv-iranui 
    - time_min=10
restart-times: 5
keep-going: True 
local-cores: 2
latency-wait: 300
printshellcmds: True 
rerun-incomplete: True 
use-conda: True
cluster-cancel: scancel